### ISSUE TITLE
Nail Issue

### ISSUE THREAD

**Issue by DracTheGreat** [JetBoom/zombiesurvival#100]
Putting multiple nails in a prop will cause the constraints to hold after the prop hits zero health.

This can be exploited pretty badly by humans in some cases. It'll buy them quite a bit of time to get away if they double nail everything.

**Comment by DracTheGreat** [comment]
Honestly, that's debatable. From my experience, by the time a barricade is needed, so many people will have died that the user will have 40+ nails in reserve. It seems that every other player buys a hammer at game start. This isn't counting the free hammers, either. 

When you have nothing else to do with it, nailing an at-risk prop is a great investment for one of the 40 extra nails that will explode from you when you inevitably die.

**Comment by Zverina** [comment]
Our experiences are pretty different. In the two different servers I have played on (main in the past and main now), people rarely get hammers. I am usually stuck with barricading because I cannot rely on others to make a good enough barricade.

This being the case, I usually spend a ton of money on extra nails (if the map has a lot of good props and I run out) or ask a friend to buy me a few so I can grab a gun.

And in the rare case that someone else DID die with a hammer + nails, there are the scavenger players that pick up anything on the ground. A few who share, most who do not.


But, yeah, I can see your point. In a server with people who /actually know how to play,/ this can be an issue.

**Comment by JetBoom** [comment]
77fea51273ae8d6938d22eba6329a665ee707dce

**Comment by DracTheGreat** [comment]
The issue is still present after your fix.
