### ISSUE TITLE
[Request - Source SDK] trigger_zombieclass check player's class

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#168]
I made a request on this way back, but now I have another small bit to ask to have added.

Can we add a keyvalue that denies the class change if the player currently is a certain zombie?

For example, a zombie can walk into the trigger to become a headcrab, but a Nightmare can walk into the trigger, but not become a headcrab.

**Comment by end360** [comment]
Seems to already be implemented with the key "onlywhenclass" Set to "disabled" to disable
Otherwise, make a comma-separated list (no spaces) with the class name. An example being "the tickle monster,bonemesh,giga gore child,nightmare"
There has to be no spaces after commas and it has to be lowercase.
[The Code](https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/entities/entities/trigger_zombieclass/init.lua#L39)
