### ISSUE TITLE
Newest gmod update breaks ZS

### ISSUE THREAD

**Issue by Alex9914** [JetBoom/zombiesurvival#232]

**Comment by Risusama** [comment]
Indeed so. The following errors show up and character models are all grey.

`lua/includes/modules/scripted_ents.lua:57: attempt to index local 't' (a nil value)
    1. Register - lua/includes/modules/scripted_ents.lua:57
        2. regscriptent - gamemodes/zombiesurvival/gamemode/sh_weaponquality.lua:185
            3. CreateWeaponOfQuality - gamemodes/zombiesurvival/gamemode/sh_weaponquality.lua:190
                4. CreateWeaponQualities - gamemodes/zombiesurvival/gamemode/sh_weaponquality.lua:249
                    5. unknown - gamemodes/zombiesurvival/gamemode/cl_init.lua:1444`
                    6. 
![image](https://user-images.githubusercontent.com/12206978/216790427-0eb11db8-93ac-4f95-9c29-31fde6841bd0.png)

**Comment by Risusama** [comment]
I started fixing this, will make a Pull Request from my repo when ready.

**Comment by Risusama** [comment]
So I added some debug logging (59fcd089976b2c4266cd5138185506cab004d006).
These show that the script tries to create a new entity "prop_gunturret_assault_q1_q2" and fails to do so, presumably because it is a "quality on top of a quality", if you get what I mean.

@JetBoom Tagging you in this just in case you have any idea on what to do. I believe most of the problems are fixed but I'm at a total loss here with these (see also PR #233)

See attached log:
[console.log](https://github.com/JetBoom/zombiesurvival/files/10678332/console.log)

**Comment by arthurgeron** [comment]
@Risusama 
Tested with latest changes from master and everything ran smoothly.
